# Generated by Django 3.1 on 2020-09-06 12:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200906_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
