# Generated by Django 3.1 on 2020-09-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cover',
            new_name='pic',
        ),
    ]
